name: Auto Update Submodules

on:
  schedule:
    - cron: '0 0 * * *' # every day at midnight UTC
  workflow_dispatch: # allows manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout meta-repo
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update submodules
        run: |
          git submodule update --remote --merge
          git add .
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -m "Auto update submodules" || echo "No changes"
          git push

      - name: Generate data.json
        run: |
          echo '{' > data.json
          echo '"updated": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"' >> data.json
          echo '}' >> data.json

      - name: Commit updated data.json
        run: |
          git add data.json
          git commit -m "Updated data.json" || echo "No changes"
          git push

      - name: Create tag
        run: |
          TAG=release-$(date +%Y%m%d%H%M%S)
          git tag "$TAG"
          git push origin "$TAG"
          echo "TAG_NAME=$TAG" >> $GITHUB_ENV
          
      - name: Create a new release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: "Release ${{ env.TAG_NAME }}"
          body: "Auto release after submodule updates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
